shop/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('greetings/', views.greetings, name='greetings'),
    path('', views.list_item, name='index'),
    path('<int:item_id>/', views.detail_item, name='detail_item'),
]

web_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
]

shop/models.py
from django.db import models


class Item(models.Model):
    name = models.CharField(max_length=30)
    price = models.IntegerField(default=0)
    
    def __str__(self):
        return self.name


class Purchase(models.Model):
    name = models.CharField(max_length=30)
    age = models.IntegerField(default=0)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    date_purchase = models.DateTimeField('date purchased')

    def __str__(self):
        return f'{self.name}, {self.age}, {self.date_purchase}'
    

shop/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from .models import Item, Purchase


def greetings(request):
    return HttpResponse('Добро пожаловать в наш магазин!')


def list_item(request):
    items = Item.objects.all()
    context = {
        'items': items
    }
    return render(request, 'list_item.html', context)


def detail_item(request, item_id):
    item = get_object_or_404(Item, id=item_id)
    context = {
        'item': item
    }
    return render(request, 'detail_item.html', context)

shop/templates/detail_item.html
<h1>{{ item.name }}</h1>
<ul>      
{% for purchase in item.purchase_set.all %}
    <li>{{ purchase.name }}, {{ purchase.age }}, {{ purchase.date_purchase }}</li>
{% endfor %}
</ul>

shop/templates/list_item.html
<h1>Item List</h1>
{% if items %}
    <ul>
    {% for item in items %}
        <li><a href="{% url 'detail_item' item.id %}">{{ item.name }}, {{ item.price }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No items are available.</p>
{% endif %}